# Deviations from Normality

In [12]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import risk_ as rv

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
hfi = rv.get_hfi_returns()
hfi = hfi["2009":"2018"]
hfi

Convertible Arbitrage  CTA Global  Distressed Securities  \
date                                                                
2009-01                 0.0491     -0.0016                 0.0082   
2009-02                 0.0164     -0.0031                -0.0122   
2009-03                 0.0235     -0.0180                 0.0022   
2009-04                 0.0500     -0.0140                 0.0387   
2009-05                 0.0578      0.0213                 0.0504   
...                        ...         ...                    ...   
2018-07                 0.0021     -0.0058                 0.0093   
2018-08                 0.0024      0.0166                 0.0002   
2018-09                 0.0034     -0.0054                 0.0050   
2018-10                -0.0073     -0.0314                -0.0158   
2018-11                -0.0068     -0.0053                -0.0193   

         Emerging Markets  Equity Market Neutral  Event Driven  \
date                                                             
2009-01           -0.0112                 0.0079        0.0132   
2009-02           -0.0133                -0.0046       -0.0091   
2009-03            0.0350                 0.0021        0.0117   
2009-04            0.0663                -0.0012        0.0337   
2009-05            0.0884                 0.0146        0.0442   
...                   ...                    ...           ...   
2018-07            0.0040                -0.0010        0.0055   
2018-08           -0.0277                 0.0004        0.0011   
2018-09           -0.0110                -0.0016        0.0032   
2018-10           -0.0315                -0.0129       -0.0257   
2018-11            0.0120                -0.0211       -0.0034   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
date                                                               
2009-01                  0.0112        0.0029            -0.0017   
2009-02                  0.0065       -0.0055            -0.0161   
2009-03                  0.0057        0.0048             0.0188   
2009-04                  0.0221        0.0127             0.0375   
2009-05                  0.0365        0.0348             0.0516   
...                         ...           ...                ...   
2018-07                  0.0022       -0.0014             0.0067   
2018-08                  0.0017       -0.0007             0.0035   
2018-09                  0.0036        0.0006            -0.0023   
2018-10                 -0.0023       -0.0096            -0.0402   
2018-11                 -0.0067       -0.0087            -0.0044   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
date                                                                      
2009-01            0.0056          0.0100         0.0282          0.0060  
2009-02            0.0006         -0.0016         0.0328         -0.0037  
2009-03            0.0125          0.0100        -0.0462          0.0008  
2009-04            0.0081          0.0342        -0.0820          0.0092  
2009-05            0.0107          0.0392         0.0008          0.0312  
...                   ...             ...            ...             ...  
2018-07           -0.0021          0.0045        -0.0052          0.0018  
2018-08            0.0050         -0.0002        -0.0214          0.0015  
2018-09            0.0028          0.0018         0.0036         -0.0022  
2018-10           -0.0080         -0.0109         0.0237         -0.0269  
2018-11            0.0119         -0.0063        -0.0021         -0.0071  

[119 rows x 13 columns]

In [14]:
pd.concat([hfi.mean(), hfi.median(), hfi.mean() > hfi.median()], axis="columns")

0       1      2
Convertible Arbitrage   0.006623  0.0045   True
CTA Global              0.000497 -0.0003   True
Distressed Securities   0.006559  0.0082  False
Emerging Markets        0.005205  0.0061  False
Equity Market Neutral   0.002556  0.0032  False
Event Driven            0.005595  0.0070  False
Fixed Income Arbitrage  0.005478  0.0050   True
Global Macro            0.002676  0.0020   True
Long/Short Equity       0.005209  0.0064  False
Merger Arbitrage        0.003716  0.0047  False
Relative Value          0.005452  0.0055  False
Short Selling          -0.010350 -0.0144   True
Funds Of Funds          0.002470  0.0039  False

In [15]:
rv.skewness(hfi).sort_values()

Equity Market Neutral    -0.896327
Funds Of Funds           -0.646908
Merger Arbitrage         -0.551065
Event Driven             -0.488821
Long/Short Equity        -0.463703
Distressed Securities    -0.254944
Emerging Markets          0.033123
CTA Global                0.052062
Relative Value            0.159953
Global Macro              0.348184
Short Selling             0.456518
Fixed Income Arbitrage    1.121453
Convertible Arbitrage     1.305911
dtype: float64

In [16]:
import scipy.stats
scipy.stats.skew(hfi)


array([ 1.30591093,  0.05206195, -0.25494434,  0.03312287, -0.89632731,
       -0.48882095,  1.12145348,  0.34818394, -0.46370341, -0.55106451,
        0.15995286,  0.45651822, -0.64690778])

In [17]:
import numpy as np
normal_rets = np.random.normal(0, .15, size=(263, 1))

In [18]:
rv.skewness(normal_rets)

-0.028506863895491744

# Kurtosis

In [19]:
rv.kurtosis(normal_rets)

2.7771048566411665

In [20]:
rv.kurtosis(hfi)

Convertible Arbitrage     6.775731
CTA Global                2.591087
Distressed Securities     3.319725
Emerging Markets          4.401636
Equity Market Neutral     5.071677
Event Driven              3.620617
Fixed Income Arbitrage    6.406941
Global Macro              3.164362
Long/Short Equity         4.115713
Merger Arbitrage          2.715238
Relative Value            4.512482
Short Selling             4.175832
Funds Of Funds            3.816132
dtype: float64

In [31]:
scipy.stats.kurtosis(normal_rets)
# This returns the exccess kurtosis greater than 3

array([-0.22289514])

In [32]:
scipy.stats.kurtosis(hfi)

array([ 3.77573087, -0.40891269,  0.31972474,  1.40163604,  2.071677  ,
        0.62061708,  3.40694074,  0.16436172,  1.11571306, -0.28476219,
        1.51248205,  1.17583189,  0.81613169])

In [33]:
scipy.stats.jarque_bera(normal_rets)

(0.5800553772316336, 0.748242849482942)

In [34]:
scipy.stats.jarque_bera(hfi)

(1885.0544854827647, 0.0)

In [35]:
rv.is_normal(normal_rets)

True

In [36]:
rv.is_normal(hfi)

False

In [37]:
hfi.aggregate(rv.is_normal)

Convertible Arbitrage     False
CTA Global                 True
Distressed Securities      True
Emerging Markets          False
Equity Market Neutral     False
Event Driven               True
Fixed Income Arbitrage    False
Global Macro               True
Long/Short Equity         False
Merger Arbitrage           True
Relative Value            False
Short Selling             False
Funds Of Funds            False
dtype: bool